### ISSUE TITLE
[feature request] disable battlEye

### ISSUE THREAD

**Issue by gpedro** [opentibiabr/client-editor#1]

**Comment by EliasMurakami** [comment]
Atalho do Tibia -> Propriedades ->
"C:\Users\xxxxx\Desktop\Tibia 12x Coisa\Tibia\bin\client.exe"

Adicione na frente de " 

--battleye

ficando assim
"C:\Users\xxxxx\Desktop\Tibia 12x Coisa\Tibia\bin\client.exe" --battleye


Essa foi uma solução que encontrei na otland, existe uma maneira de tirar isso direto no binario do client.
Ela meio que remove o pop-up dizendo que o batleEye precisa ser iniciado.
