### ISSUE TITLE
[ERROR] Unable to replace Tibia Login WebService [linux]

### ISSUE THREAD

**Issue by victorperin** [opentibiabr/client-editor#3]
For some reason i get this message on linux. Do not know why yet.

**Comment by victorperin** [comment]
Got the same error on windows.

![image](https://user-images.githubusercontent.com/5847145/81538938-d42d8180-9345-11ea-9939-ca42c4fd0af8.png)

**Comment by gpedro** [comment]
which client are you using? i think you choose the wrong exe

**Comment by victorperin** [comment]
I'm trying with the latest, 12.31.9810.

The executable was wrong, but tested again, with 12.00 on the correct file and it worked.

Tried the same approach with 12.31 and got this output:
```
$ ./client-editor-linux-x64 ~/.local/share/CipSoft\ GmbH/Tibia/packages/Tibia1231-ot/bin/client http://test/login.php

[INFO] Backuping client to BKP1589307882-client
[INFO] Searching for Tibia RSA... 
[INFO] Tibia RSA found!
[PATCH] Tibia RSA replaced to OTServ RSA!
[INFO] Searching for Login WebService... 
[ERROR] Cannot replace webserivce to http://test/login.php, because the new loginWebService length is greater then -171.
```

**Comment by gpedro** [comment]
@victorperin can you send me this binary ?

**Comment by victorperin** [comment]
[client.tar.gz](https://github.com/opentibiabr/client-editor/files/4618981/client.tar.gz)

**Comment by LawCodeAi** [comment]
Mesmo problema aqui, alguma novidade?

**Comment by gpedro** [comment]
can you test with this version?
[client-editor-windows-1230.zip](https://github.com/opentibiabr/client-editor/files/4843683/client-editor-windows-1230.zip)
[client-editor-linux-1230.zip](https://github.com/opentibiabr/client-editor/files/4843682/client-editor-linux-1230.zip)
[client-editor-darwin-1230.zip](https://github.com/opentibiabr/client-editor/files/4843681/client-editor-darwin-1230.zip)

**Comment by whiteprojectcrixu** [comment]
are you have maybe for 1240? when i use this on linux wine show me error
```
crixu@home:~/ProjectX/Tibia/Tibia 12.40/bin$ wine client.exe
0009:err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x7bc77a96
```



> can you test with this version?
> [client-editor-windows-1230.zip](https://github.com/opentibiabr/client-editor/files/4843683/client-editor-windows-1230.zip)
> [client-editor-linux-1230.zip](https://github.com/opentibiabr/client-editor/files/4843682/client-editor-linux-1230.zip)
> [client-editor-darwin-1230.zip](https://github.com/opentibiabr/client-editor/files/4843681/client-editor-darwin-1230.zip)
